### ISSUE TITLE
Feature Req: Exemptions

### ISSUE THREAD

**Issue by matt2222** [jwensley2/DownloadStatusBar#17]
Great work reviving the idea behind previous add-ons like this. Moving the bar into the main page is very innovative and I'm glad to have it back...

Just a feature request if possible, to be able to specify file extensions that won't be shown in the bar when they are downloaded, as per some previous add-ons like this. So for example, one might want to exempt image file extensions when downloading multiple images.... 

Cheers!

**Comment by jwensley2** [comment]
This should be fairly easy to add since it's basically the same as the auto clearing. I'll try to get it into the next version.

**Comment by jwensley2** [comment]
I've released a beta version for 1.7 with this feature if you would like to test it.
https://addons.mozilla.org/en-US/firefox/addon/wx-download-status-bar/versions/beta?page=1#version-1.7.0beta1

**Comment by matt2222** [comment]
Thanks for the response and sorry for the delay in responding. 

I've installed 1.7.0beta1 on two machines, but am not able to get the exemption to work, even after restarting FF and uninstalling the add-on and reinstalling it. Screenshot of my settings and the bar still appearing attached...

![sshot-3](https://user-images.githubusercontent.com/34482962/34326284-cc08a25c-e8a0-11e7-9e94-e0ac55894844.jpg)
